#!/usr/bin/env python3
from __future__ import annotations

import argparse
import re
import sqlite3
from pathlib import Path

import psycopg2
from psycopg2 import sql
from psycopg2.extras import execute_values

DEFAULT_SQLITE_PATH = Path(__file__).resolve().parent / "stock_codes.db"
DEFAULT_DATABASE_URL = "postgresql://zanbo@/stockapp"
BATCH_SIZE = 2000


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="迁移 SQLite 数据到 PostgreSQL")
    parser.add_argument("--sqlite-path", default=str(DEFAULT_SQLITE_PATH), help="SQLite 数据库路径")
    parser.add_argument("--database-url", default=DEFAULT_DATABASE_URL, help="PostgreSQL 连接串")
    parser.add_argument("--drop-existing", action="store_true", help="迁移前删除 PostgreSQL 现有同名表")
    parser.add_argument("--batch-size", type=int, default=BATCH_SIZE, help="批量写入大小")
    parser.add_argument("--table", default="", help="只迁移单张表")
    return parser.parse_args()


def qident(name: str):
    return sql.Identifier(name)


def map_sqlite_type(declared_type: str, is_identity: bool = False) -> str:
    dtype = (declared_type or "").strip().upper()
    if is_identity:
        return "BIGINT GENERATED BY DEFAULT AS IDENTITY"
    if "INT" in dtype:
        return "BIGINT"
    if any(x in dtype for x in ["REAL", "FLOA", "DOUB"]):
        return "DOUBLE PRECISION"
    if any(x in dtype for x in ["NUM", "DEC", "BOOL"]):
        return "NUMERIC"
    if "BLOB" in dtype:
        return "BYTEA"
    return "TEXT"


def user_tables(src: sqlite3.Connection) -> list[str]:
    rows = src.execute(
        "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name"
    ).fetchall()
    return [r[0] for r in rows]


def table_sql(src: sqlite3.Connection, table: str) -> str:
    row = src.execute("SELECT sql FROM sqlite_master WHERE type='table' AND name=?", (table,)).fetchone()
    return row[0] or ""


def create_table(dst, src: sqlite3.Connection, table: str, drop_existing: bool) -> list[str]:
    pragma = src.execute(f"PRAGMA table_info({table})").fetchall()
    create_sql = table_sql(src, table)
    identity_candidates: set[str] = set()
    if create_sql:
        for col_name, col_type in re.findall(
            r'"?([A-Za-z_][A-Za-z0-9_]*)"?\s+([A-Za-z0-9() ]+?)\s+PRIMARY\s+KEY\s+AUTOINCREMENT',
            create_sql,
            flags=re.I,
        ):
            identity_candidates.add(col_name)

    pk_cols = [row[1] for row in pragma if row[5]]
    column_defs: list[str] = []
    ordered_cols: list[str] = []
    for cid, name, col_type, notnull, dflt_value, pk in pragma:
        is_identity = name in identity_candidates and len(pk_cols) == 1
        pg_type = map_sqlite_type(col_type, is_identity=is_identity)
        parts = [f'"{name}"', pg_type]
        if notnull:
            parts.append("NOT NULL")
        ordered_cols.append(name)
        column_defs.append(" ".join(parts))

    if pk_cols:
        quoted_pk = ", ".join(f'"{c}"' for c in pk_cols)
        column_defs.append(f"PRIMARY KEY ({quoted_pk})")

    create_stmt = f'CREATE TABLE IF NOT EXISTS "{table}" (\n  ' + ",\n  ".join(column_defs) + "\n)"
    with dst.cursor() as cur:
        if drop_existing:
            cur.execute(sql.SQL("DROP TABLE IF EXISTS {} CASCADE").format(qident(table)))
        cur.execute(create_stmt)
    dst.commit()
    return ordered_cols


def recreate_indexes(dst, src: sqlite3.Connection, table: str):
    index_rows = src.execute(f"PRAGMA index_list({table})").fetchall()
    col_types = {
        row[1]: str(row[2] or "").upper()
        for row in src.execute(f"PRAGMA table_info({table})").fetchall()
    }
    with dst.cursor() as cur:
        for row in index_rows:
            seq, index_name, unique = row[0], row[1], row[2]
            if index_name.startswith("sqlite_autoindex"):
                continue
            info_rows = src.execute(f"PRAGMA index_info({index_name})").fetchall()
            cols = [r[2] for r in info_rows if r[2]]
            if not cols:
                continue
            if unique and any("TEXT" in col_types.get(col, "") for col in cols):
                expr = " || '|' || ".join([f"COALESCE({sql.Identifier(c).as_string(dst)}::text, '')" for c in cols])
                stmt = sql.SQL("DROP INDEX IF EXISTS {}").format(sql.Identifier(index_name))
                cur.execute(stmt)
                cur.execute(
                    sql.SQL("CREATE UNIQUE INDEX {} ON {} (md5({}))").format(
                        sql.Identifier(index_name),
                        sql.Identifier(table),
                        sql.SQL(expr),
                    )
                )
                continue
            ident_cols = sql.SQL(", ").join(sql.Identifier(c) for c in cols)
            stmt = sql.SQL("CREATE {} INDEX IF NOT EXISTS {} ON {} ({})").format(
                sql.SQL("UNIQUE") if unique else sql.SQL(""),
                sql.Identifier(index_name),
                sql.Identifier(table),
                ident_cols,
            )
            cur.execute(stmt)
    dst.commit()


def primary_key_columns(src: sqlite3.Connection, table: str) -> list[str]:
    return [row[1] for row in src.execute(f"PRAGMA table_info({table})").fetchall() if row[5]]


def copy_table(dst, src: sqlite3.Connection, table: str, columns: list[str], batch_size: int):
    col_list = ", ".join(f'"{c}"' for c in columns)
    select_sql = f'SELECT {col_list} FROM "{table}"'
    rows = src.execute(select_sql)
    total = 0
    pk_cols = primary_key_columns(src, table)
    if pk_cols:
        update_cols = [c for c in columns if c not in pk_cols]
        if update_cols:
            conflict_stmt = sql.SQL(" ON CONFLICT ({}) DO UPDATE SET {}").format(
                sql.SQL(", ").join(sql.Identifier(c) for c in pk_cols),
                sql.SQL(", ").join(
                    sql.SQL("{} = EXCLUDED.{}").format(sql.Identifier(c), sql.Identifier(c)) for c in update_cols
                ),
            )
        else:
            conflict_stmt = sql.SQL(" ON CONFLICT ({}) DO NOTHING").format(
                sql.SQL(", ").join(sql.Identifier(c) for c in pk_cols)
            )
    else:
        conflict_stmt = sql.SQL(" ON CONFLICT DO NOTHING")
    insert_stmt = sql.SQL("INSERT INTO {} ({}) VALUES %s").format(
        sql.Identifier(table),
        sql.SQL(", ").join(sql.Identifier(c) for c in columns),
    ) + conflict_stmt
    buf = []
    with dst.cursor() as cur:
        for row in rows:
            buf.append(tuple(row))
            if len(buf) >= batch_size:
                execute_values(cur, insert_stmt.as_string(dst), buf, page_size=batch_size)
                total += len(buf)
                print(f"  {table}: copied {total} rows")
                buf.clear()
        if buf:
            execute_values(cur, insert_stmt.as_string(dst), buf, page_size=batch_size)
            total += len(buf)
    dst.commit()
    print(f"  {table}: done {total} rows")


def reset_identity_sequences(dst, src: sqlite3.Connection, table: str):
    pragma = src.execute(f"PRAGMA table_info({table})").fetchall()
    if len([r for r in pragma if r[5]]) != 1:
        return
    pk = next((r for r in pragma if r[5]), None)
    if not pk:
        return
    col_name = pk[1]
    create_sql = table_sql(src, table)
    if not re.search(rf'"?{re.escape(col_name)}"?\s+[A-Za-z0-9() ]+\s+PRIMARY\s+KEY\s+AUTOINCREMENT', create_sql or "", flags=re.I):
        return
    seq_name = f"{table}_{col_name}_seq"
    with dst.cursor() as cur:
        cur.execute(
            sql.SQL(
                "SELECT setval(%s, COALESCE((SELECT MAX({}) FROM {}), 1), true)"
            ).format(sql.Identifier(col_name), sql.Identifier(table)),
            (seq_name,),
        )
    dst.commit()


def main() -> int:
    args = parse_args()
    sqlite_path = Path(args.sqlite_path).resolve()
    if not sqlite_path.exists():
        raise SystemExit(f"SQLite 数据库不存在: {sqlite_path}")

    src = sqlite3.connect(sqlite_path)
    try:
        dst = psycopg2.connect(args.database_url)
        dst.autocommit = False
        try:
            tables = user_tables(src)
            if args.table:
                tables = [t for t in tables if t == args.table]
                if not tables:
                    raise SystemExit(f"未找到指定表: {args.table}")
            print(f"开始迁移，共 {len(tables)} 张表")
            for table in tables:
                print(f"[schema] {table}")
                columns = create_table(dst, src, table, args.drop_existing)
                recreate_indexes(dst, src, table)
                copy_table(dst, src, table, columns, args.batch_size)
                reset_identity_sequences(dst, src, table)
            print("迁移完成")
        finally:
            dst.close()
    finally:
        src.close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
